import = ["/home/ezeire/.config/alacritty/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Jetbrains mono"
style = "Bold"

[font.bold_italic]
family = "Jetbrains mono"
style = "Bold italic"

[font.italic]
family = "Jetbrains mono"
style = "Italic"

[font.normal]
family = "Jetbrains mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.96
title = "Alacritty"
