#! /bin/sh

#--------------------------------------------------------
# ( autostart )
#--------------------------------------------------------
#killall -9 sxhkd nitrogen polybar picom
sxhkd &
nitrogen --restore &
~/scripts/keyboard-reset.sh &
xsetroot -cursor_name left_ptr &
polybar example &
picom &
#--------------------------------------------------------

#--------------------------------------------------------
# ( workspace )
#--------------------------------------------------------
bspc monitor -d  ﬦ ﬦ   
# bspc monitor -d www dev bok msc spk oth
#--------------------------------------------------------

# pgrep -x sxhkd > /dev/null || sxhkd &


#--------------------------------------------------------
# (frames and gaps)
#--------------------------------------------------------
bspc config border_width        2
bspc config window_gap          6

bspc config normal_border_color  "#323232"
bspc config active_border_color  "#8e4b8c"
bspc config focused_border_color "#161616"

bspc config presel_feedback_color "fd2e59"
#--------------------------------------------------------

#--------------------------------------------------------
# (windows config) 
#--------------------------------------------------------
bspc config split_ratio          0.5

bspc config single_monocle	     false

bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
#--------------------------------------------------------

#--------------------------------------------------------
# (windows rule)
#--------------------------------------------------------
# bspc rule -a dmenu_run state=floating rectangle=99x22+610+90
bspc rule -a Firefox desktop='^1'
bspc rule -a discord desktop='^5'
#--------------------------------------------------------
